name: adamw
weight_decay: 0
lr: 3e-4
use_jax_param_groups: true
aux_lr_factor: 0.02
bulk_lr_divide_by_hidden_size: true
ln_wd: ${.weight_decay}
bias_wd: 0.0
bulk_wd: ${.weight_decay}
emb_unemb_wd: 0.0
beta1: 0.9
beta2: 0.999
eps: 1e-8
